# Generated by Django 4.1.7 on 2023-02-19 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercury_drops', '0002_remove_user__admin_alter_user__id_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='_cpf',
            new_name='cpf',
        ),
    ]
